name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sogajeffrey/rclone-backup:latest
    - name: Login to docker 
      run: docker login -u sogajeffrey -p $DOCKER_TOKEN
    - name: Push to Docker Hub
      run: docker push sogajeffrey/rclone-backup:latest
